server:
  port: 8081
  origin: ${ORIGIN:*}
  servlet:
    context-path: /queries
spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: queries
  rabbitmq:
    addresses: ${RABBITMQ_URI:amqp://guest:guest@localhost:5672}  
  data:
    mongodb:
        uri: ${MONGO_URI:mongodb://localhost:27017/query}
microservice:
  exchange: "core-demo"
  queue: "demo.querieshandles"
  routingKey: "org.example.#"

